#!/usr/bin/env bash
# One-shot VM setup for Oracle Cloud Always Free (Ampere A1).
# Run on a fresh Oracle Linux 9 or Ubuntu 22.04 instance as the `opc` / `ubuntu` user.
#
# What it does:
#   1. Installs Docker + Docker Compose plugin.
#   2. Installs OCI CLI (for block-volume snapshots — Oracle's snapshot quota is
#      generous on Always Free, so this is the cheapest backup story).
#   3. Clones the repo to /opt/gcpallet.
#   4. Generates a strong PB admin password and writes deploy/.env.
#   5. Pulls the docker images, starts the stack, prints the next-step URLs.
#
# Re-runnable: detects existing installs and skips them.
# Idempotent: safe to run twice; only writes a new .env on first run.

set -euo pipefail

REPO_URL="https://github.com/EVOMINDMAZE/GC_Pallet_SaaS.git"
APP_DIR="/opt/gcpallet"
PB_ADMIN_PASSWORD_LENGTH=24

# ---- 0. Sanity checks ----
if [ "$(id -u)" -eq 0 ]; then
  echo "ERROR: do not run as root. Use the default opc/ubuntu user with sudo."
  exit 1
fi

if ! command -v sudo >/dev/null; then
  echo "ERROR: sudo is not installed."
  exit 1
fi

# ---- 1. Detect OS ----
. /etc/os-release
OS_ID="${ID:-unknown}"
echo ">>> Detected OS: ${PRETTY_NAME:-$OS_ID}"

# ---- 2. Install Docker + Compose ----
if command -v docker >/dev/null 2>&1; then
  echo ">>> docker already installed: $(docker --version)"
else
  echo ">>> installing docker …"
  case "$OS_ID" in
    ubuntu|debian)
      sudo apt-get update
      sudo apt-get install -y ca-certificates curl gnupg
      sudo install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/${OS_ID}/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      sudo chmod a+r /etc/apt/keyrings/docker.gpg
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${OS_ID} \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
      sudo apt-get update
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      ;;
    ol|rhel|centos|rocky|almalinux|fedora)
      sudo dnf -y install dnf-plugins-core
      sudo dnf config-manager --add-repo https://download.docker.com/linux/${OS_ID}/docker-ce.repo
      case "$OS_ID" in
        fedora) sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin ;;
        *) sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin ;;
      esac
      sudo systemctl enable --now docker
      ;;
    *)
      echo "ERROR: unsupported OS for auto-install: $OS_ID"
      echo "Install Docker manually: https://docs.docker.com/engine/install/"
      exit 1
      ;;
  esac
  sudo usermod -aG docker "$USER"
  echo ">>> docker installed. NOTE: you must log out and back in for the docker group to take effect,"
  echo "    then re-run this script."
  exit 0
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: docker compose plugin not available. Install docker-compose-plugin."
  exit 1
fi

# ---- 3. Install OCI CLI (for block-volume snapshots) ----
if ! command -v oci >/dev/null 2>&1; then
  echo ">>> installing OCI CLI (for backups) …"
  sudo dnf -y install python3 python3-pip 2>/dev/null || sudo apt-get install -y python3 python3-pip
  # OCI CLI is pip-installable; the system Python often lacks PEP 517 on
  # minimal images, so use --break-system-packages if needed.
  if pip3 install --user oci-cli 2>&1 | tail -2; then
    :
  else
    pip3 install --user --break-system-packages oci-cli
  fi
  echo ">>> OCI CLI installed. Run 'oci setup config' to authenticate."
  echo "    (You can defer this — backups will fail until OCI is configured, but the app works without them.)"
fi

# ---- 4. Clone the repo ----
if [ ! -d "$APP_DIR" ]; then
  echo ">>> cloning $REPO_URL into $APP_DIR …"
  sudo mkdir -p "$APP_DIR"
  sudo chown "$USER:$USER" "$APP_DIR"
  git clone "$REPO_URL" "$APP_DIR"
  cd "$APP_DIR"
else
  echo ">>> $APP_DIR already exists, pulling latest …"
  cd "$APP_DIR"
  git pull --ff-only
fi

# ---- 5. Write .env on first run ----
ENV_FILE="deploy/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo ">>> generating $ENV_FILE …"
  PASSWORD=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$PB_ADMIN_PASSWORD_LENGTH")
  cat > "$ENV_FILE" <<EOF
# Generated by init-vm.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ").
# Fill in DOMAIN before the first 'docker compose up'. The rest is ready.

# Public DNS name pointing at this VM. Caddy will auto-issue a Let's Encrypt cert.
DOMAIN=example.com

# PocketBase superuser (created via the /_/ admin UI the first time).
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=$PASSWORD

# Baked into the frontend bundle at build time. Same as the public origin
# the user visits (so the SDK can call /api/pb/* via the same origin).
NEXT_PUBLIC_PB_URL=https://DOMAIN_REPLACE_ME
EOF
  echo ">>> wrote $ENV_FILE with a random PB admin password."
  echo "    → edit it now: set DOMAIN=your-real-domain and update NEXT_PUBLIC_PB_URL to match."
  echo "    → save the ADMIN_PASSWORD somewhere safe; you'll need it to log in at /_/."
  echo
  echo "PAUSED: edit $APP_DIR/$ENV_FILE, then re-run this script."
  exit 0
fi

# ---- 6. Validate .env ----
# shellcheck disable=SC1090
. "$ENV_FILE"
: "${DOMAIN:?DOMAIN must be set in $ENV_FILE}"
: "${ADMIN_EMAIL:?ADMIN_EMAIL must be set}"
: "${ADMIN_PASSWORD:?ADMIN_PASSWORD must be set}"

# Auto-replace NEXT_PUBLIC_PB_URL if still set to the placeholder.
if grep -q "DOMAIN_REPLACE_ME" "$ENV_FILE"; then
  sed -i "s|DOMAIN_REPLACE_ME|$DOMAIN|" "$ENV_FILE"
  echo ">>> patched NEXT_PUBLIC_PB_URL → https://$DOMAIN"
  . "$ENV_FILE"
fi

# ---- 7. Build and start ----
echo ">>> building images …"
cd "$APP_DIR"
docker compose --env-file "$ENV_FILE" -f deploy/docker-compose.yml build

echo ">>> starting stack …"
docker compose --env-file "$ENV_FILE" -f deploy/docker-compose.yml up -d

echo
echo "==================================================================="
echo "  GC Pallet is starting up."
echo
echo "  App URL:        https://$DOMAIN"
echo "  PB admin UI:    https://$DOMAIN/_/"
echo "  Admin email:    $ADMIN_EMAIL"
echo "  Admin password: (saved in $APP_DIR/$ENV_FILE)"
echo
echo "  First-time steps:"
echo "    1. Make sure your DNS A record for $DOMAIN points at this VM's public IP."
echo "    2. Open https://$DOMAIN/_/ in a browser and log in with the admin creds."
echo "       (Caddy will get the cert on the first request — DNS must be live first.)"
echo "    3. Done. The app is live."
echo
echo "  Useful commands:"
echo "    cd $APP_DIR"
echo "    docker compose -f deploy/docker-compose.yml ps           # status"
echo "    docker compose -f deploy/docker-compose.yml logs -f      # tail logs"
echo "    sudo bash deploy/scripts/backup.sh                       # manual backup"
echo "==================================================================="
